version: "2.1"

services:
    node:
        build: .
        container_name: music_node
        ports:
            - ${NODE_PORT}:${NODE_PORT}
        environment:
            - NODE_ENV=${ENVIRONMENT}
        volumes:
            - ./:/app
        command: ${START_COMMAND}

